@startuml
'https://plantuml.com/class-diagram

class ListMakerApp {
    +main()
    +start()
}

class ListMakerController {
    +addNewItemButtonPressed()
}

class todoListItemsTable {

}

ListMakerApp - ListMakerController
ListMakerController -- todoListItemsTable
javafx.Application <|-- ListMakerApp

@enduml